openapi: 3.0.3
info:
  title: SparkLayer Coding Test
  version: 1.0.11

paths:
  /:
    post:
      summary: Add a To-Do to the list
      operationId: createToDo
      requestBody:
        description: Create a new To-Do Task
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/To-Do"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/To-Do"
        "400":
          description: Invalid input
    get:
      summary: Gets the To-Do List
      operationId: getToDos
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/To-Do-List"
    delete:
      summary: Delete a To-Do by ID
      operationId: deleteToDo
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: The ID of the Todo to delete
    responses:
      "200":
        description: Todo successfully deleted
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Todo deleted
      "400":
        description: Invalid or missing ID
      "404":
        description: Todo not found
        
components:
  schemas:
    To-Do-List:
      additionalProperties: false
      type: array
      items:
        $ref: "#/components/schemas/To-Do"
    To-Do:
      type: object
      additionalProperties: false
      required:
        - title
        - description
      properties:
        title:
          type: string
          example: Go for a jog
        description:
          type: string
          example: run 4km around the river
